import type { Lead } from './types'

export const LEADS: Lead[] = [
  {
    id: 'lead-1',
    name: 'Alex Johnson',
    title: 'Marketing Director',
    company: 'Innovate Corp',
    email: 'alex.j@innovate.com',
    phone: '+1-202-555-0176',
    status: 'New',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=AJ',
    profile: 'Alex is the Marketing Director at Innovate Corp, a fast-growing tech startup specializing in AI-driven analytics. They recently secured Series B funding. Alex has shown interest in marketing automation tools and has downloaded a whitepaper on lead generation.',
    activity: [
      { id: 'act-1-1', type: 'Email', date: '2023-10-26', notes: 'Initial outreach email sent.' },
    ],
  },
  {
    id: 'lead-2',
    name: 'Samantha Rodriguez',
    title: 'VP of Sales',
    company: 'Quantum Solutions',
    email: 's.rodriguez@quantum.co',
    phone: '+1-310-555-0188',
    status: 'Contacted',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=SR',
    profile: 'Samantha is the VP of Sales at Quantum Solutions, a large enterprise in the logistics sector. The company is looking to overhaul its CRM system. Samantha has 15 years of experience in sales leadership and is focused on improving team efficiency.',
    activity: [
      { id: 'act-2-1', type: 'Call', duration: '15m 20s', date: '2023-10-25', notes: 'Introductory call. Discussed current CRM pain points. Follow-up scheduled.' },
      { id: 'act-2-2', type: 'Email', date: '2023-10-22', notes: 'Initial contact.' },
    ],
  },
  {
    id: 'lead-3',
    name: 'Benjamin Carter',
    title: 'CTO',
    company: 'DataStream Inc.',
    email: 'ben.c@datastream.io',
    phone: '+1-415-555-0132',
    status: 'Qualified',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=BC',
    profile: 'Benjamin is the CTO of DataStream Inc., a mid-sized company in the data warehousing space. They are actively looking for cloud migration services. Ben has a strong technical background and is the primary decision-maker for technology purchases.',
    activity: [
      { id: 'act-3-1', type: 'Meeting', date: '2023-10-27', notes: 'Product demo. Strong interest shown in enterprise package.' },
      { id: 'act-3-2', type: 'Call', duration: '30m 05s', date: '2023-10-20', notes: 'Technical discovery call. Assessed current infrastructure.' },
    ],
  },
  {
    id: 'lead-4',
    name: 'Olivia Martinez',
    title: 'Product Manager',
    company: 'Creative Labs',
    email: 'olivia.m@creativelabs.net',
    phone: '+1-646-555-0159',
    status: 'Lost',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=OM',
    profile: 'Olivia is a Product Manager at Creative Labs, a digital design agency. She was exploring collaboration tools but the company has decided to build an in-house solution. Budget constraints were a major factor.',
    activity: [
      { id: 'act-4-1', type: 'Email', date: '2023-10-19', notes: 'Received email stating they are no longer looking for a solution.' },
      { id: 'act-4-2', type: 'Call', duration: '10m 15s', date: '2023-10-15', notes: 'Brief call to discuss pricing. Seemed hesitant about the cost.' },
    ],
  },
  {
    id: 'lead-5',
    name: 'William Chen',
    title: 'Operations Manager',
    company: 'Global Health',
    email: 'w.chen@globalhealth.org',
    phone: '+1-773-555-0199',
    status: 'Unqualified',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=WC',
    profile: 'William is an Operations Manager at Global Health, a non-profit organization. While interested in the product, their scale of operations is too small for the current product offering. They do not meet the minimum user count for the enterprise plan.',
    activity: [
      { id: 'act-5-1', type: 'Email', date: '2023-10-18', notes: 'Follow-up email confirming they are not a good fit at this time.' },
    ],
  },
    {
    id: 'lead-6',
    name: 'Emily Davis',
    title: 'CEO',
    company: 'Synergy Enterprises',
    email: 'emily.d@synergy.com',
    phone: '+1-214-555-0145',
    status: 'Won',
    avatarUrl: 'https://placehold.co/100x100/E2E8F0/475569.png?text=ED',
    profile: 'Emily is the CEO of Synergy Enterprises, a consulting firm. They have signed a two-year contract for the premium package. Key factors were the AI features and seamless integration capabilities. The deal was closed after a successful pilot program.',
    activity: [
      { id: 'act-6-1', type: 'Meeting', date: '2023-10-28', notes: 'Contract signed. Onboarding process initiated.' },
      { id: 'act-6-2', type: 'Call', duration: '45m 00s', date: '2023-10-15', notes: 'Final negotiation call.' },
      { id: 'act-6-3', type: 'Email', date: '2023-10-01', notes: 'Pilot program kickoff.' },
    ],
  },
]
