import { firestore } from '@/lib/firebase';
import { 
  collection, 
  getDocs, 
  addDoc, 
  updateDoc, 
  deleteDoc, 
  doc, 
  query, 
  orderBy, 
  serverTimestamp, 
  Timestamp 
} from 'firebase/firestore';

export interface LeadCampaign {
  id: string;
  name: string;
  description?: string;
  isBuiltIn: boolean;
  isActive: boolean;
  createdBy?: string;
  createdAt?: Timestamp | Date | string | null;
}

export const BUILT_IN_CAMPAIGNS: Omit<LeadCampaign, 'id'>[] = [
  { name: 'Outbound', description: 'Standard outbound cold calling and dialer campaigns', isBuiltIn: true, isActive: true },
  { name: 'Door-to-Door', description: 'Field sales door-to-door canvas campaigns', isBuiltIn: true, isActive: true },
  { name: 'MultiSite', description: 'Multi-site account expansion campaigns', isBuiltIn: true, isActive: true },
  { name: 'LPO Network Onboarding', description: 'Leads converted from Australia Post LPO onboarding expressions of interest', isBuiltIn: true, isActive: true },
  { name: 'Account Manager Generated', description: 'Leads sourced directly by Account Managers', isBuiltIn: true, isActive: true },
  { name: 'Franchisee Generated', description: 'Leads generated by local franchisees', isBuiltIn: true, isActive: true },
  { name: 'Inbound', description: 'Inbound web, phone, or marketing inquiries', isBuiltIn: true, isActive: true },
  { name: 'Customer Success Generated', description: 'Leads generated by Customer Success reps', isBuiltIn: true, isActive: true },
  { name: 'Nurture Campaign', description: 'Leads enrolled in automated nurture sequences', isBuiltIn: true, isActive: true }
];

export async function getLeadCampaigns(): Promise<LeadCampaign[]> {
  try {
    const q = query(collection(firestore, 'lead_campaigns'), orderBy('createdAt', 'desc'));
    const snap = await getDocs(q);
    
    const dbCampaigns: LeadCampaign[] = snap.docs.map(docSnap => ({
      id: docSnap.id,
      ...docSnap.data()
    } as LeadCampaign));

    // Combine built-in campaigns with DB campaigns
    const existingNames = new Set(dbCampaigns.map(c => c.name.toLowerCase()));
    
    const missingBuiltIns: LeadCampaign[] = BUILT_IN_CAMPAIGNS
      .filter(b => !existingNames.has(b.name.toLowerCase()))
      .map(b => ({
        id: `builtin_${b.name.toLowerCase().replace(/[^a-z0-9]/g, '_')}`,
        ...b
      }));

    return [...dbCampaigns, ...missingBuiltIns];
  } catch (err) {
    console.error('Error fetching lead campaigns:', err);
    // Return default built-in campaigns on error or before collection exists
    return BUILT_IN_CAMPAIGNS.map(b => ({
      id: `builtin_${b.name.toLowerCase().replace(/[^a-z0-9]/g, '_')}`,
      ...b
    }));
  }
}

export async function createLeadCampaign(payload: {
  name: string;
  description?: string;
  createdBy?: string;
}): Promise<string> {
  const nameTrimmed = payload.name.trim();
  if (!nameTrimmed) {
    throw new Error('Campaign name cannot be empty');
  }

  const existing = await getLeadCampaigns();
  if (existing.some(c => c.name.toLowerCase() === nameTrimmed.toLowerCase())) {
    throw new Error(`A campaign with the name "${nameTrimmed}" already exists.`);
  }

  const newDocRef = await addDoc(collection(firestore, 'lead_campaigns'), {
    name: nameTrimmed,
    description: payload.description?.trim() || '',
    isBuiltIn: false,
    isActive: true,
    createdBy: payload.createdBy || 'Unknown User',
    createdAt: serverTimestamp()
  });

  return newDocRef.id;
}

export async function toggleLeadCampaignStatus(campaignId: string, currentIsActive: boolean): Promise<void> {
  if (campaignId.startsWith('builtin_')) {
    // For built-in items not yet in Firestore, create doc with overridden isActive state
    const campaignName = campaignId.replace('builtin_', '').replace(/_/g, ' ');
    const matchedBuiltIn = BUILT_IN_CAMPAIGNS.find(b => b.name.toLowerCase() === campaignName.toLowerCase());
    
    await addDoc(collection(firestore, 'lead_campaigns'), {
      name: matchedBuiltIn?.name || campaignName,
      description: matchedBuiltIn?.description || '',
      isBuiltIn: true,
      isActive: !currentIsActive,
      createdAt: serverTimestamp()
    });
    return;
  }

  const docRef = doc(firestore, 'lead_campaigns', campaignId);
  await updateDoc(docRef, {
    isActive: !currentIsActive
  });
}

export async function deleteLeadCampaign(campaignId: string): Promise<void> {
  if (campaignId.startsWith('builtin_')) {
    throw new Error('Built-in system campaigns cannot be deleted.');
  }

  const docRef = doc(firestore, 'lead_campaigns', campaignId);
  await deleteDoc(docRef);
}
