// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'Android options have not been configured yet.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'iOS options have not been configured yet.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjmbHw0qCZeyZLnTC3k7mpd4-wYscNXBc',
    appId: '1:683616418101:web:a4cdcb614f438df146747c',
    messagingSenderId: '683616418101',
    projectId: 'mailplus-outbound-leads-crm',
    authDomain: 'mailplus-outbound-leads-crm.firebaseapp.com',
    storageBucket: 'mailplus-outbound-leads-crm.firebasestorage.app',
  );
}
